[theme]
primaryColor = "#10B981"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F4F6F8"
textColor = "#0F172A"
font = "sans serif"

[server]
runOnSave = true
headless = false

[browser]
gatherUsageStats = false
